######################################################################
# Automatically generated by qmake (3.0) Mi Nov 16 08:16:52 2016
######################################################################

TEMPLATE = app
TARGET = perlIDE
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
